codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  # temporarily allow any level of coverage until proper testing can be done
  range: "0...100"

  status:
    # same here
    project: off
    patch: off
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: yes
