name: Build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6

      - name: Start up Postgres and Redis
        run: docker-compose up -d

      - name: Test and generate coverage report
        run:
          sbt clean coverage test coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./core/target/scala-2.12/scoverage-report/scoverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Shutting down Postgres and Redis
        run: docker-compose down